
["Spawn Chances"]

	#Configure Mob spawn weight & min/max group size. Set weight to 0 to disable.
	["Spawn Chances"."Flying Fox"]
		#Range: 0 ~ 64
		min = 1
		#Range: 0 ~ 64
		max = 5
		#Range: 0 ~ 500
		weight = 5

