
#Settings related to the chaos system
[chaos]
	#Players will not experience chaos events until they have a respawn point set
	noEventsUntilHasBed = true
	#The maximum chaos value that a player can reach
	#Range: > 1
	maxChaos = 10000000

[world]

	#World generation settings. You must restart your game after changing these.
	#Changes will not be reflected in chunks that have already generated, only new ones.
	[world.18]

		#Settings for ores. Setting either vein count or vein size to zero (0) will stop that ore from generating.
		#Mod dimensions will use the overworld config.
		#Note that most of these config are disabled by default. They are provided so that which gems are in each dimension can be customized.
		[world.18.ores]

			[world.18.ores.chaos]
				#Number of veins per chunk that the ore spawns in. Rarity is rolled against first and no veins will generate in the chunk if the check fails.
				#Range: > 0
				count = 4
				#Size of veins
				#Range: 0 ~ 1000
				size = 11
				#The chance (1 in N) of generating in any given chunk. Higher numbers means more rare.
				#Range: > 0
				rarity = 2
				#Minimum Y-coordinate (base height) of veins
				#Range: > -2147483648
				minHeight = -90
				#Maximum Y-coordinate (highest level) of veins
				#Range: > -2147483648
				maxHeight = 10
				#The chance (out of 1) that the ore will not generate if exposed to air.
				#Range: 0.0 ~ 1.0
				discardChanceOnAirExposure = 0.5

