
["Configs for Skillcloaks"]
	#true = Cloaks are cosmetic only. false = Cloaks have abilities (Default = false)
	"Cosmetic only" = false
	#Will villagers have a chance to offer a sack in a trade (Default = true)
	"Sack trades" = true
	#Will the Nitwit give the Black Sack if offered a stack of Emeralds? (Default = true)
	"Black Sack trade" = true
	#How much armor will the cloaks give to the wearer. Only values greater than 0 will have any effect (Default = 0)
	"Skill Cloak armor" = 0
	#How much armor will the infernal cloak give to the wearer. Only values greater than 0 will have any effect (Default = 12)
	"Infernal Cloak armor" = 12
	#How much attack will the infernal cloak give to the wearer. Only values greater than 0 will have any effect (Default = 4)
	"Infernal Cloak attack" = 4
	#The percentage of health the target has to have left for Slayer Cloak to activate (Default = 0.25 = 25%)
	#Range: 0.0 ~ 1.0
	"Slayer threshold" = 0.25
	#The percent chance for the Ranging Cloak or the Fletching Cloak to return an arrow (Default = 0.5 = 50%)
	#Range: 0.0 ~ 1.0
	"Arrow return chance" = 0.5
	#The percent chance for the Attack Cloak to prevent armor durability loss (Default = 0.5 = 50%)
	#Range: 0.0 ~ 1.0
	"Armor durability loss prevent chance" = 0.5
	#The percent chance for the Runecraft Cloak to prevent tool durability loss (Default = 0.5 = 50%)
	#Range: 0.0 ~ 1.0
	"Tool durability loss prevent chance" = 0.5
	#The bonus range in blocks your bonemeal reaches while wearing the Farming Cloak (Default = 2 = 3x3 area)
	"Number of blocks your bonemeal area is extended" = 2
	#The amount your visibility value is multiplied by while wearing the Thieving Cloak. Lower values makes you less likely to be spotted by enemies (Default = 0.2 = 20%)
	#Range: 0.0 ~ 1.0
	"Thieving cloak visibility multiplier" = 0.2
	#The Amount of luck the Fishing Cloak gives (Default = 3)
	"Fishing luck" = 3
	#The Amount of fortune the Mining Cloak gives (Default = 1)
	"Mining luck" = 1
	#The Amount of knockback resistance the Strength Cloak gives (Default = 1)
	"Strength knockback resistance" = 1
	#Should the Firemaking Cloak allow you to place down torches with sticks? (Default = true)
	"Firemaking torch" = true
	#The chance for a stick to be used when placing down a torch with the Firemaking Cloak (Default = 100 = 100%)
	#Range: 0 ~ 100
	"Firemaking stick chance" = 100
	#Should wearing the Firemaking Cloak give light if Lucent is installed (Default = true)
	"Lucent compat" = true
	#The amount of time in ticks for the cooldown of Defence Cloak (Default = 24000)
	"Defence cooldown" = 24000
	#The amount your gained exhaustion is multiplied by when wearing the Agility Cloak. Lower numbers mean you get less exhaustion (Default = 0.5 = 50%)
	#Range: 0.0 ~ 1.0
	"Agility exhaustion reducer" = 0.5

